repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.4.1" # Update to the latest compatible version
    hooks:
      - id: mypy
  - repo: https://github.com/psf/black
    rev: 23.9.1 # Update to the latest stable version
    hooks:
      - id: black
